import type { ComponentProps, ComponentType } from 'react'
import {
  Add24Regular,
  ArrowDown24Regular,
  ArrowRedo24Regular,
  ArrowUndo24Regular,
  ArrowUp24Regular,
  BranchFork24Regular,
  ChevronRight24Regular,
  ClipboardPaste24Regular,
  Code24Regular,
  Comment24Regular,
  Copy24Regular,
  Cut24Regular,
  Delete24Regular,
  Dismiss24Regular,
  Document24Regular,
  Folder24Regular,
  FolderOpen24Regular,
  Highlight24Regular,
  Image24Regular,
  Navigation24Regular,
  Note24Regular,
  PaintBrush24Regular,
  Play24Regular,
  Print24Regular,
  Save24Regular,
  Search24Regular,
  Settings24Regular,
  Share24Regular,
  Subtract24Regular,
  Table24Regular,
  TextAlignCenter24Regular,
  TextAlignLeft24Regular,
  TextAlignRight24Regular,
  TextBold24Regular,
  TextBulletListLtr24Regular,
  TextColor24Regular,
  FontDecrease24Regular,
  FontIncrease24Regular,
  TextItalic24Regular,
  TextNumberListLtr24Regular,
  TextStrikethrough24Regular,
  TextSubscript24Regular,
  TextSuperscript24Regular,
  TextT24Regular,
  TextUnderline24Regular,
  MoreHorizontal24Regular,
  ZoomIn24Regular,
  ZoomOut24Regular,
} from '@fluentui/react-icons'

type Name =
  | 'menu' | 'file' | 'folder' | 'plus' | 'save' | 'open' | 'print' | 'play' | 'settings'
  | 'trash' | 'copy' | 'up' | 'down' | 'code' | 'image' | 'table' | 'diagram' | 'text'
  | 'list' | 'note' | 'divider' | 'chevron' | 'close' | 'bold' | 'italic' | 'underline' | 'undo' | 'redo'
  | 'paste' | 'cut' | 'formatPainter' | 'fontIncrease' | 'fontDecrease' | 'strike' | 'subscript' | 'superscript'
  | 'highlight' | 'fontColor' | 'alignLeft' | 'alignCenter' | 'alignRight' | 'numberList' | 'search'
  | 'comment' | 'share' | 'more' | 'zoomIn' | 'zoomOut'

type FluentIconComponent = ComponentType<ComponentProps<typeof Add24Regular>>

const icons: Record<Name, FluentIconComponent> = {
  menu: Navigation24Regular,
  file: Document24Regular,
  folder: Folder24Regular,
  plus: Add24Regular,
  save: Save24Regular,
  open: FolderOpen24Regular,
  print: Print24Regular,
  play: Play24Regular,
  settings: Settings24Regular,
  trash: Delete24Regular,
  copy: Copy24Regular,
  up: ArrowUp24Regular,
  down: ArrowDown24Regular,
  code: Code24Regular,
  image: Image24Regular,
  table: Table24Regular,
  diagram: BranchFork24Regular,
  text: TextT24Regular,
  list: TextBulletListLtr24Regular,
  note: Note24Regular,
  divider: Subtract24Regular,
  chevron: ChevronRight24Regular,
  close: Dismiss24Regular,
  bold: TextBold24Regular,
  italic: TextItalic24Regular,
  underline: TextUnderline24Regular,
  undo: ArrowUndo24Regular,
  redo: ArrowRedo24Regular,
  paste: ClipboardPaste24Regular,
  cut: Cut24Regular,
  formatPainter: PaintBrush24Regular,
  fontIncrease: FontIncrease24Regular,
  fontDecrease: FontDecrease24Regular,
  strike: TextStrikethrough24Regular,
  subscript: TextSubscript24Regular,
  superscript: TextSuperscript24Regular,
  highlight: Highlight24Regular,
  fontColor: TextColor24Regular,
  alignLeft: TextAlignLeft24Regular,
  alignCenter: TextAlignCenter24Regular,
  alignRight: TextAlignRight24Regular,
  numberList: TextNumberListLtr24Regular,
  search: Search24Regular,
  comment: Comment24Regular,
  share: Share24Regular,
  more: MoreHorizontal24Regular,
  zoomIn: ZoomIn24Regular,
  zoomOut: ZoomOut24Regular,
}

export function Icon({ name, size = 18, className, ...props }: { name: Name; size?: number; className?: string } & Omit<ComponentProps<typeof Add24Regular>, 'fontSize'>) {
  const Glyph = icons[name]
  return <Glyph aria-hidden="true" className={className} style={{ width: size, height: size, fontSize: size, flexShrink: 0, ...props.style }} {...props} />
}
